services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: devroot

  # api:
  #   image: node:22-alpine
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./api:/usr/src/app
  #   environment:
  #     PORT: "3000"
  #     DB_HOST: db
  #     DB_USER: app
  #     DB_PASSWORD: app
  #     DB_NAME: app
  #   command: sh -c "npm i && node app.js"
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
